// Import axios for making HTTP requests to Google's reCAPTCHA API
import axios from 'axios';

/**
 * Verify reCAPTCHA token with Google's reCAPTCHA API
 * This function validates that the user interaction is legitimate and not automated
 * @param {string} recaptchaToken - The reCAPTCHA token generated by the frontend
 * @returns {Object} Verification result with success status and additional data
 */
export const verifyRecaptcha = async (recaptchaToken) => {
  // Skip reCAPTCHA in development/test for easier testing
  if (process.env.NODE_ENV !== 'production') {
    return { success: true, message: 'reCAPTCHA skipped in development' };
  }

  try {
    // Check if reCAPTCHA token is provided
    if (!recaptchaToken) {
      return { success: false, message: 'reCAPTCHA token is required' };
    }

    // Make POST request to Google's reCAPTCHA verification endpoint
    const response = await axios.post(
      'https://www.google.com/recaptcha/api/siteverify', // Google's reCAPTCHA verification URL
      null, // No request body needed for POST
      {
        params: {
          secret: process.env.RECAPTCHA_SECRET_KEY, // Your server-side secret key from environment variables
          response: recaptchaToken, // The token received from the frontend
        },
      }
    );

    // Extract response data from Google's API
    const data = response.data;

    // Check if reCAPTCHA verification was successful
    if (data.success) {
      return { 
        success: true, 
        score: data.score, // reCAPTCHA v3 score (0.0 - 1.0), higher = more likely human
        message: 'reCAPTCHA verification successful' 
      };
    }

    // Return failure details if reCAPTCHA verification failed
    return {
      success: false,
      message: 'reCAPTCHA verification failed',
      errors: data['error-codes'] || ['Unknown error'], // Include any error codes from Google
    };
  } catch (error) {
    // Log detailed error for debugging purposes
    console.error('❌ reCAPTCHA verification error:', error);
    
    // Return user-friendly error message
    return { 
      success: false, 
      message: 'Error verifying reCAPTCHA. Please try again.' 
    };
  }
};